<div>
    <x-filament::section>
        <x-slot name="heading">
            Two-Factor Authentication (2FA)
        </x-slot>
        <x-slot name="description">
            Add additional security to your account using two-factor authentication.
        </x-slot>

        @if($state === "idle")
            <div class="space-y-4">
                <p class="text-sm text-gray-500 dark:text-gray-400">
                    When two-factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's Google Authenticator, Authy, or Microsoft Authenticator application.
                </p>
                <x-filament::button wire:click="enable2FA" color="primary">
                    Enable 2FA
                </x-filament::button>
            </div>
        @elseif($state === "confirming")
            <div class="space-y-6">
                <h3 class="text-lg font-medium text-gray-950 dark:text-white">Finish enabling two factor authentication.</h3>
                
                <div class="p-4 bg-primary-50 dark:bg-primary-950/20 text-primary-600 dark:text-primary-400 rounded-xl border border-primary-100 dark:border-primary-900/50">
                    <h4 class="font-bold mb-2">Step-by-Step Setup Guide:</h4>
                    <ol class="list-decimal list-inside space-y-1 text-sm">
                        <li>Download an authenticator app (like Google Authenticator or Authy) on your mobile device.</li>
                        <li>Open the app and select the option to add a new account via QR code.</li>
                        <li>Scan the QR code below using your device's camera.</li>
                        <li>Enter the 6-digit code generated by the app into the input field below to confirm.</li>
                    </ol>
                </div>

                <div class="flex justify-center p-4 bg-white rounded-lg inline-block">
                    {!! $qrCodeSvg !!}
                </div>

                <div class="max-w-xs space-y-2">
                    <label class="text-sm font-medium leading-6 text-gray-950 dark:text-white">Verification Code</label>
                    <x-filament::input.wrapper>
                        <x-filament::input
                            type="text"
                            wire:model="confirmationCode"
                            placeholder="123456"
                            class="text-center tracking-widest text-lg"
                        />
                    </x-filament::input.wrapper>
                    @error("confirmationCode")
                        <span class="text-sm text-danger-600 dark:text-danger-400">{{ $message }}</span>
                    @enderror
                </div>

                <div class="flex gap-4 mt-4">
                    <x-filament::button wire:click="confirm2FA" color="primary">
                        Confirm & Enable
                    </x-filament::button>
                    <x-filament::button wire:click="cancelEnable" color="gray" variant="outlined">
                        Cancel
                    </x-filament::button>
                </div>
            </div>
        @elseif($state === "enabled")
            <div class="space-y-4">
                <div class="p-4 bg-success-50 dark:bg-success-950/20 text-success-600 dark:text-success-400 rounded-xl border border-success-100 dark:border-success-900/50">
                    <strong>You have enabled two factor authentication.</strong>
                </div>

                <div class="flex gap-4">
                    <x-filament::button wire:click="regenerateRecoveryCodes" color="gray" variant="outlined">
                        Regenerate Recovery Codes
                    </x-filament::button>
                    <x-filament::button wire:click="disable2FA" color="danger" variant="outlined">
                        Disable 2FA
                    </x-filament::button>
                </div>
            </div>
        @elseif($state === "verifying_disable" || $state === "verifying_regenerate")
            <div class="space-y-6">
                <h3 class="text-lg font-medium text-gray-950 dark:text-white">
                    {{ $state === "verifying_disable" ? "Disable Two-Factor Authentication" : "Regenerate Recovery Codes" }}
                </h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                    Please confirm access to your account by entering the authentication code provided by your authenticator application.
                </p>

                <div class="max-w-xs space-y-2">
                    <label class="text-sm font-medium leading-6 text-gray-950 dark:text-white">Verification Code</label>
                    <x-filament::input.wrapper>
                        <x-filament::input
                            type="text"
                            wire:model="verificationCode"
                            placeholder="123456"
                            class="text-center tracking-widest text-lg"
                        />
                    </x-filament::input.wrapper>
                    @error("verificationCode")
                        <span class="text-sm text-danger-600 dark:text-danger-400">{{ $message }}</span>
                    @enderror
                </div>

                <div class="flex gap-4 mt-4">
                    <x-filament::button wire:click="{{ $state === 'verifying_disable' ? 'confirmDisable2FA' : 'confirmRegenerateRecoveryCodes' }}" color="primary">
                        Confirm
                    </x-filament::button>
                    <x-filament::button wire:click="cancelVerification" color="gray" variant="outlined">
                        Cancel
                    </x-filament::button>
                </div>
            </div>
        @elseif($state === "showing_recovery_codes")
            <div class="space-y-6">
                <div class="p-4 bg-warning-50 dark:bg-warning-950/20 text-warning-600 dark:text-warning-400 rounded-xl border border-warning-100 dark:border-warning-900/50">
                    <h4 class="font-bold mb-2">Store these recovery codes in a secure password manager.</h4>
                    <p class="text-sm">They can be used to recover access to your account if your two factor authentication device is lost. This is the <strong>only time</strong> you will be able to see these codes.</p>
                </div>

                <div class="grid grid-cols-2 gap-4 max-w-sm">
                    @foreach($recoveryCodes as $code)
                        <div class="p-2 bg-gray-50 dark:bg-gray-800 rounded font-mono text-sm text-center text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700">
                            {{ $code }}
                        </div>
                    @endforeach
                </div>

                <div class="flex items-center gap-4 mt-4">
                    <x-filament::button wire:click="downloadRecoveryCodes" color="gray" variant="outlined" icon="heroicon-o-arrow-down-tray">
                        Download
                    </x-filament::button>
                    <x-filament::button wire:click="hideRecoveryCodes" color="primary" :disabled="!$hasDownloadedCodes">
                        Done
                    </x-filament::button>
                    @if(!$hasDownloadedCodes)
                        <span class="text-sm text-gray-500">You must download your recovery codes before continuing.</span>
                    @endif
                </div>
            </div>
        @endif
    </x-filament::section>
</div>
